const FEATURES = [
  ['Parallelism','Lines relate to one another by repeating, contrasting, or expanding an idea.\nExample: "The heavens declare the glory of God; the skies proclaim the work of his hands." (Psalm 19:1)'],
  ['Imagery','Vivid metaphors and pictures communicate spiritual truths.\nExample: "The LORD is my shepherd." (Psalm 23:1)'],
  ['Concrete Language','Physical images express abstract emotions or realities.\nExample: "He set my feet upon a rock." (Psalm 40:2)'],
  ['Merism','Two opposite extremes represent the whole.\nExample: "The LORD will keep your going out and your coming in." (Psalm 121:8)'],
  ['Chiasm','A mirrored A-B-C-B\'-A\' structure emphasizes the center or a reversal.\nExample: "Whoever exalts himself will be humbled, and whoever humbles himself will be exalted." (Matthew 23:12)'],
  ['Inclusio (Bookends)','A repeated phrase or theme frames the poem.\nExample: Psalm 8 begins and ends: "O LORD, our Lord, how majestic is thy name in all the earth!"'],
  ['Acrostics','Verses or sections follow the Hebrew alphabet.\nExample: Psalm 119 has 22 sections, one for each Hebrew letter.'],
  ['Repetition','Words, phrases, or refrains are intentionally repeated for emphasis.\nExample: "For his steadfast love endures forever." (Psalm 136)'],
  ['Emotional Movement','The poem progresses emotionally, often from lament to trust to praise.\nExample: Psalm 13 moves from "How long, O LORD?" to praise.'],
  ['Symbolic Numbers','Certain numbers carry literary or theological significance.\nExample: Psalm 119 has 22 sections, each with 8 verses.'],
  ['Sound Patterns','Alliteration, assonance, wordplay, and puns enrich the Hebrew text.\nExample: \'adam and \'adamah echo each other in Genesis 2-3.']
];
const FEATURE_IDS = ['parallelism','imagery','concrete_language','merism','chiasm','inclusio','acrostics','repetition','emotional_movement','symbolic_numbers','sound_patterns'];
const SCOPE='https://www.googleapis.com/auth/drive.appdata', FILE='psalms-analysis-annotations.json';
let psalms=[], chapter=0, feature=0, annotations=JSON.parse(localStorage.getItem('psalmAnnotations')||'{"highlights":[],"notes":{}}'), token=null, activeWord=null;
const $=id=>document.getElementById(id);
function normalizeAnnotationKey(value){const parts=value.split('|');if(parts.length!==4)return value;const featureIndex=Number(parts[1]);return Number.isInteger(featureIndex)&&FEATURE_IDS[featureIndex]?`${parts[0]}|${FEATURE_IDS[featureIndex]}|${parts[2]}|${parts[3]}`:value;}
function migrateLocalAnnotations(){annotations.highlights=(annotations.highlights||[]).map(normalizeAnnotationKey);const migratedNotes={};Object.entries(annotations.notes||{}).forEach(([k,v])=>{migratedNotes[normalizeAnnotationKey(k)]=v;});annotations.notes=migratedNotes;saveLocal();}
function key(psalm, verse, word){ return `${psalm}|${FEATURE_IDS[feature]}|${verse}|${word}`; }
function saveLocal(){ localStorage.setItem('psalmAnnotations',JSON.stringify(annotations)); }
migrateLocalAnnotations();
function toggleWord(s){const k=s.dataset.key;if(annotations.notes[k])return;const on=annotations.highlights.includes(k);annotations.highlights=on?annotations.highlights.filter(x=>x!==k):[...annotations.highlights,k];s.classList.toggle('highlight',!on);saveLocal();sync();}
function render(){ $('title').textContent=`Psalm ${chapter+1}`; $('description').textContent=FEATURES[feature][1]; const out=$('text'); out.innerHTML=''; psalms[chapter].forEach(v=>{ const span=document.createElement('span'); span.className='verse'; span.textContent=v.verse+' '; out.append(span); let i=0; v.text.split(/(\s+)/).forEach(part=>{ if(/^\s+$/.test(part)){out.append(part);return;} const s=document.createElement('span'); const k=key(chapter+1,v.verse,i++); s.className='word '+(annotations.notes[k]?'note':annotations.highlights.includes(k)?'highlight':''); s.textContent=part; s.dataset.key=k; let timer; const finish=()=>{clearTimeout(timer); if(s.isPointerDown){s.isPointerDown=false;toggleWord(s);}}; s.addEventListener('pointerdown',e=>{e.preventDefault();s.isPointerDown=true;timer=setTimeout(finish,450);s.setPointerCapture?.(e.pointerId);}); s.addEventListener('pointermove',e=>{if(s.isPointerDown)finish();}); s.addEventListener('pointerup',finish); s.addEventListener('pointercancel',()=>{clearTimeout(timer);s.isPointerDown=false;}); s.addEventListener('dblclick',()=>openNote(k,v.verse,part)); out.append(s); }); out.append('\n\n'); }); }
function openNote(k,verse,word){ activeWord={k}; $('noteTitle').textContent=`Psalm ${chapter+1}:${verse} note`; $('noteText').value=annotations.notes[k]||''; $('noteDialog').showModal(); }
$('noteDialog').addEventListener('close',()=>{ if($('noteDialog').returnValue==='save'){const v=$('noteText').value.trim(); if(v) annotations.notes[activeWord.k]=v; else delete annotations.notes[activeWord.k]; annotations.highlights=[...new Set([...annotations.highlights,activeWord.k])]; saveLocal(); render(); sync();} if($('noteDialog').returnValue==='delete'){delete annotations.notes[activeWord.k]; saveLocal(); render(); sync();} });
for(let i=0;i<150;i++){const o=document.createElement('option');o.value=i;o.textContent=`Psalm ${i+1}`;$('chapter').append(o);} FEATURES.forEach((f,i)=>{const o=document.createElement('option');o.value=i;o.textContent=f[0];$('feature').append(o);});
$('chapter').onchange=e=>{chapter=+e.target.value;render();}; $('feature').onchange=e=>{feature=+e.target.value;render();}; $('previous').onclick=()=>{chapter=Math.max(0,chapter-1);$('chapter').value=chapter;render();}; $('next').onclick=()=>{chapter=Math.min(149,chapter+1);$('chapter').value=chapter;render();};
async function driveFetch(url,options={}){options.headers={...(options.headers||{}),Authorization:`Bearer ${token}`};const r=await fetch(url,options);if(!r.ok)throw Error(await r.text());return r;}
async function sync(){if(!token)return;try{const q=encodeURIComponent(`name='${FILE}' and 'appDataFolder' in parents and trashed=false`);const list=await driveFetch(`https://www.googleapis.com/drive/v3/files?q=${q}&spaces=appDataFolder&fields=files(id)`);const files=(await list.json()).files; if(files.length){const r=await driveFetch(`https://www.googleapis.com/drive/v3/files/${files[0].id}?alt=media`);const remote=await r.json();annotations.highlights=[...new Set([...annotations.highlights,...(remote.highlights||[])])];annotations.notes={...(remote.notes||{}),...annotations.notes};await driveFetch(`https://www.googleapis.com/upload/drive/v3/files/${files[0].id}?uploadType=media`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify(annotations)});}else{const boundary='psalmsBoundary';const body=`--${boundary}\r\nContent-Type: application/json; charset=UTF-8\r\n\r\n${JSON.stringify({name:FILE,parents:['appDataFolder']})}\r\n--${boundary}\r\nContent-Type: application/json\r\n\r\n${JSON.stringify(annotations)}\r\n--${boundary}--`;await driveFetch('https://www.googleapis.com/upload/drive/v3/files?uploadType=multipart',{method:'POST',headers:{'Content-Type':`multipart/related; boundary=${boundary}`},body});}saveLocal();render();$('status').textContent='Synced with Google Drive.';}catch(e){$('status').textContent='Sync unavailable; local annotations are still saved.';}}
function markSignedIn(accessToken){token=accessToken;$('signIn').textContent='Already signed in to Google';localStorage.setItem('googleSignedIn','true');sync();}
function signIn(){if(!window.PSALMS_GOOGLE_CLIENT_ID||window.PSALMS_GOOGLE_CLIENT_ID.startsWith('YOUR_')){alert('Set PSALMS_GOOGLE_CLIENT_ID in web/config.js first.');return;}const c=google.accounts.oauth2.initTokenClient({client_id:window.PSALMS_GOOGLE_CLIENT_ID,scope:SCOPE,callback:r=>{if(r.access_token)markSignedIn(r.access_token);}});c.requestAccessToken();}
function restoreGoogleSession(){if(!window.PSALMS_GOOGLE_CLIENT_ID||window.PSALMS_GOOGLE_CLIENT_ID.startsWith('YOUR_')||!window.google?.accounts?.oauth2)return;const c=google.accounts.oauth2.initTokenClient({client_id:window.PSALMS_GOOGLE_CLIENT_ID,scope:SCOPE,callback:r=>{if(r.access_token)markSignedIn(r.access_token);}});c.requestAccessToken({prompt:''});}
$('signIn').onclick=signIn; fetch('psalms_kjv.json').then(r=>r.json()).then(d=>{psalms=d.chapters.map(chapterData=>chapterData.verses||[]);render();}).catch(()=>{$('status').textContent='Unable to load the Psalms text.';}); window.addEventListener('load',restoreGoogleSession);
